### ISSUE TITLE
Cloud Media Uploads broken with tenancy

### ISSUE THREAD

**Issue by MarkKropf** [joas8211/payload-tenancy#20]
Hello,

Thank you for building this 👏 

I'm using the [Cloud Upload](https://github.com/payloadcms/plugin-cloud-storage) plugin to keep my media in a storage bucket. I'm able to upload while logged into a tenant (tested both path & user strats) and the file gets uploaded. I'm not however able to GET the image via any combination of paths to the asset. While uploading, I get the following error:

```
[18:14:30] ERROR (payload): TypeError: Cannot read properties of undefined (reading 'skipTenancyUploadAfterReadHook')
    at /Volumes/GenericUser/GenericUser/payload-cms/node_modules/payload-tenancy/dist/hooks/upload.js:67:41
    at step (/Volumes/GenericUser/GenericUser/payload-cms/node_modules/payload-tenancy/dist/hooks/upload.js:44:23)
    at Object.next (/Volumes/GenericUser/GenericUser/payload-cms/node_modules/payload-tenancy/dist/hooks/upload.js:25:53)
    at /Volumes/GenericUser/GenericUser/payload-cms/node_modules/payload-tenancy/dist/hooks/upload.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Volumes/GenericUser/GenericUser/payload-cms/node_modules/payload-tenancy/dist/hooks/upload.js:15:12)
    at /Volumes/GenericUser/GenericUser/payload-cms/node_modules/payload-tenancy/dist/hooks/upload.js:61:16
    at /Volumes/GenericUser/GenericUser/payload-cms/node_modules/payload/src/collections/operations/find.ts:223:24
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Volumes/GenericUser/GenericUser/payload-cms/node_modules/payload/src/collections/operations/find.ts:220:7
```

The media upload gets mapped to a correct looking URL: 
*User Strategy*
```
http://localhost:3000/media/images/random-image.jpg
``` 

*Path Strategy*
```
http://localhost:3000/root/media/images/random-image.jpg
```

But both result in a failure to retrieve the media asset:
```
Cannot GET /media/images/random-image.jpg
```

**Comment by joas8211** [comment]
I created an update (v1.1.3). Can you confirm if there still is a problem?

**Comment by MarkKropf** [comment]
Thank you 🙏
