### ISSUE TITLE
Postgres Error: "invalid reference to FROM-clause entry for table"

### ISSUE THREAD

**Issue by Bradleykingz** [joas8211/payload-tenancy#40]
I've set up a simple project with the following config:

```ts
export default buildConfig({
  admin: {
    user: Users.slug,
    bundler: webpackBundler(),
  },
  editor: lexicalEditor({}),
  collections: [
    Media,
    Tenants,
    Users
  ],
  typescript: {
    outputFile: path.resolve(__dirname, 'payload-types.ts'),
  },
  graphQL: {
    schemaOutputFile: path.resolve(__dirname, 'generated-schema.graphql'),
  },
  globals: [
    Footer
  ],
  plugins: [
    tenancy({
      isolationStrategy: "domain"
    }),
  ],
  db: postgresAdapter({
    pool: {
      connectionString: process.env.DATABASE_URI,
    },
  }),
})
```

And here's my `Footer` global:

```ts
export const Footer: GlobalConfig = {
  slug: 'footer',
  access: {
    update: isAdmin,
  },
  fields: [
    {
      name: 'tenant',
      type: 'relationship',
      relationTo: 'tenants',
      hidden: true,
    },
    {
      name: 'columns',
      type: 'array',
      admin: {
        description: "The columns for your footer.",
        components: {
          RowLabel: ({data, index}: any) => data?.columnTitle || `Column ${index}`
        }
      },
      fields: [
        {
          name: "columnTitle",
          label: "Column Title",
          type: "text",
          required: true,
        },
      ],
    },
  ],
}
```
But I get the following error:

```
[11:35:46] ERROR (payload): error: invalid reference to FROM-clause entry for table "tenants"
    at /home/bradleyk/IdeaProjects/retrobie/retrobie-backend/node_modules/pg/lib/client.js:526:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /home/bradleyk/IdeaProjects/retrobie/retrobie-backend/node_modules/src/node-postgres/session.ts:64:19
    at find (/home/bradleyk/IdeaProjects/retrobie/retrobie-backend/node_modules/@payloadcms/db-postgres/src/find/findMany.ts:97:28)
    at Object.findGlobal (/home/bradleyk/IdeaProjects/retrobie/retrobie-backend/node_modules/@payloadcms/db-postgres/src/findGlobal.ts:18:7)
    at findOne (/home/bradleyk/IdeaProjects/retrobie/retrobie-backend/node_modules/payload/src/globals/operations/findOne.ts:53:15)
    at handler (/home/bradleyk/IdeaProjects/retrobie/retrobie-backend/node_modules/payload/src/globals/requestHandlers/findOne.ts:28:22)
```

Any ideas?

**Comment by Bradleykingz** [comment]
I found the problem. It's with how the access function was written.

```ts
export const isAuthorizedTenant: Access = async ({ req }) => {
  const domain = req.hostname
  
  return  {
    "tenant.domains.domain": {
      equals: domain
    }
  }
}
```

It doesn't translate well from MongoDB.
